### ISSUE TITLE
error on start

### ISSUE THREAD

**Issue by skelgaard** [nicolas-lang/Factorio.LongWarehouses#1]
16.238 Loading mod nco-LongWarehouses 0.2.1 (data-updates.lua)
  16.239 Script @__nco-LongWarehouses__/data-updates.lua:1: data-updates
  16.239 Error ModManager.cpp:1574: Failed to load mod "nco-LongWarehouses": ...o-LongWarehouses__/data/compatibility/aai-containers.lua:15: attempt to index local 'whTechLogistic2' (a nil value)
stack traceback:
	...o-LongWarehouses__/data/compatibility/aai-containers.lua:15: in main chunk
	[C]: in function 'require'
	__nco-LongWarehouses__/data-updates.lua:2: in main chunk
  16.240 Loading mod core 0.0.0 (data.lua)
  16.407 Checksum for core: 818230012
  16.463 Error ModManager.cpp:1574: Error in assignID: recipe-category with name 'crafting' does not exist.

**Comment by nicolas-lang** [comment]
I'll look into this today or tomorrow after work.

In the meantime try enabling "Enable Basic Logistic Warehouses" and "Enable Logistic System Warehouses" in the mod's startup settings.

**Comment by skelgaard** [comment]
i don't even get into game,, this comes during loading the game... it may be a mod conflict .... would you like the whole log posted ?

**Comment by nicolas-lang** [comment]
The bug should be in one of the comptibility scripts with other mods, if you have only the long warehouses enabled, the game should load,  allowing you to change the mod settings and re-enable all other mods.

**Comment by nicolas-lang** [comment]
I would expect the issue to be fixed with the new release, please retest.

**Comment by skelgaard** [comment]
works :)
