### ISSUE TITLE
Server console spam

### ISSUE THREAD

**Issue by elementalistic** [nicolas-lang/Factorio.LongWarehouses#4]
So I've loaded up the mod on my server and now I'm getting a bunch of spam, it looks like you've left some debug log's uncommented in the last release.

lib/lib_warehouse.lua:242
script/control.lua:161

https://i.imgur.com/AgNMx9H.png

**Comment by nicolas-lang** [comment]
Thanks for the report, I'll have a look for the next release.

**Comment by nicolas-lang** [comment]
should be fixed in latest release. Feel free to re-open if you encounter additional undesired messages.
